version: "3.9" # optional since v1.27.0
services:
  ocr_app:
    build: .
    container_name: fastapi-ocrapp
    # command: uvicorn --host 0.0.0.0 --port 80 app.main:app --reload
    ports:
      - "8000:80"
    volumes:
      - .:/ocr_app
